[context.production.environment]
  REACT_APP_CHAIN_ID = "80001"
  REACT_APP_ENABLE_HISTORY = "true"

[context."staging".environment]
  REACT_APP_CHAIN_ID = "80001"
  REACT_APP_ENABLE_HISTORY = "true"

[context."master".environment]
  REACT_APP_CHAIN_ID = "80001"
  REACT_APP_ENABLE_HISTORY = "true"

[context.deploy-preview.environment]
  REACT_APP_CHAIN_ID = "80001"
  REACT_APP_ENABLE_HISTORY = "true"

[build]
  command = "yarn workspace @splash/webapp build"
  publish = "packages/splash-webapp/build"
  NODE_OPTIONS = "--max_old_space_size=4096"
